# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bc7265d55fe2d7d6babf6db5183cc9716212f21f818f72c2e49a63b2378320406ffb30ab225fa8094e38a0d8f5e5a813f8c8a613f23492ff53ee876a3d39e00

test:
  secret_key_base: cfca0bcd6458820d0c63374105a14ef03a9246c91b4191dc9ef707c4b651a9b20b4f2b5dfcdfac14e30b081b72d83ee203ffd948e64ff509060daee8bc3eec6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
